version: '3'
services:
  frp:
    network_mode: host
    image: zhenshaw/frp
    container_name: frp
    restart: always
    ports:
      - 8080:8080
    volumes:
      - $PWD/conf:/conf
    command: "frpc"

